services:
  nuxt:
    build:
      context: ./nuxt
      dockerfile: Dockerfile
    volumes:
      - ./nuxt:/app
      - node_modules:/app/node_modules
    ports:
      - "51080:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development

volumes:
  node_modules: