version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "51080:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - NODE_ENV=development

volumes:
  node_modules: